version: 2
jobs:
  build_latest:
    docker:
      - image: docker:18.06.3-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t quay.io/appvia/gcloud-kubectl-helm:$CIRCLE_SHA1 .
      - run:
          name: Push image latest
          command: |
            docker tag quay.io/appvia/gcloud-kubectl-helm:$CIRCLE_SHA1 quay.io/appvia/gcloud-kubectl-helm:latest
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/gcloud-kubectl-helm:$CIRCLE_SHA1
            docker push quay.io/appvia/gcloud-kubectl-helm:latest
  build_tag:
    docker:
      - image: docker:18.06.3-dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t quay.io/appvia/gcloud-kubectl-helm:$CIRCLE_TAG .
      - run:
          name: Push image tag
          command: |
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/gcloud-kubectl-helm:$CIRCLE_TAG

workflows:
  version: 2
  build_and_upload_latest:
    jobs:
      - build_latest:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
  build_and_upload_tag:
    jobs:
      - build_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
